[package]
name = "velum"
version = "0.1.0"
description = "Turn a folder or a local site into a Tor onion service in a few clicks."
authors = ["Velum contributors"]
license = "MIT"
edition = "2021"
rust-version = "1.77"

[lib]
name = "velum_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-dialog = "2"
tauri-plugin-shell = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tiny_http = "0.12"
rand = "0.8"
base32 = "0.5"
uuid = { version = "1", features = ["v4"] }
directories = "5"
anyhow = "1"
thiserror = "1"
qrcode = { version = "0.14", default-features = false, features = ["svg"] }
chrono = { version = "0.4", features = ["serde"] }

